[package]
name = "box_dest_receiver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
comfy-table = "7.1.4"
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.72"
