/*-------------------------------------------------------------------------
 *
 * needed_pg_headers.h
 *    Generated by build.rs
 *-------------------------------------------------------------------------
 */

#include "postgres.h"
#include "access/tupdesc.h"
#include "executor/tuptable.h"
#include "tcop/dest.h"
#include "fmgr.h"
#include "utils/syscache.h"
#include "utils/lsyscache.h"

#include "static_inline_c_funcs.h"
